### ISSUE TITLE
@Yimura

### ISSUE THREAD

**Issue by 7HA7MA77** [Yimura/Portfolio#1]
Hi. Sorry for creating issue here, but @gir is blocking my every thread made on YimMenu github.
He doing very bad stuff, he closing my ideas requests and making that updates as "hey guys i made great improvement!"..

I made even post about it but he closed that too.. I can send you screenshots, i think what he doing is pathetic, is bad for project
and.. i just wanted to give my propositions for improvements, to eventually make the menu better, it's really not cool that he striking my threads just bcs he personally dont like me.. he should have in mind good of projects, and he should grow up, thats all.

**Comment by 7HA7MA77** [comment]
you can see in closed issues, 8threads closed by him in just last 24h, and there is more.. one of idea he "realised", and said its his idea.. pathetic tbh. If he would made it in a good way, at least.. but i proposed to make it possible to delete saved vehicles when hold shift, like teleports, then GUI with question if user really want to delete vehicle... he made instaed SPAM OF D*MN X'es.. not only spam but easy to missclick, no asking if user is sure about delete.. bro, if i can, i just please, take his permissions to manage issues, that's all, and.. thank You very much, peace! o/

**Comment by 7HA7MA77** [comment]
( LINKS PROVIDED:
original thread, closed by gir: https://github.com/YimMenu/YimMenu/issues/2350
his pathetic copy, made worse way than original idea: https://github.com/YimMenu/YimMenu/pull/2354
even clearly visible, my idea is 2350, his number is 2354.. i can provide more examples, but dont want to spam, peace, yo! :) )

**Comment by Yimura** [comment]
You know, acting how you do doesn't really entice people to actually help. You're temporary blocked from interacting with any repository on the YimMenu organisation. I have talked to gir and told him to ignore any messages coming from you.

In regards to your issue #2350 and gir's pull request #2354, it's normal that his number is higher because his pull request is the implementation of your issue. You can't really complain because your issue got implemented in a different way from how you wanted it to be implemented. How something gets implemented is up to one of the contributors (gir in this case), if you want it to be implemented differently you either open an improvement issue or you open a PR and change the code yourself.

**Comment by Yimura** [comment]
Neither do I have the time to be spending my free time working with children and their little disputes between each-other.

I barely get the time to work on YimMenu so if you want us to be really be productive stop making issues in a conversational way, be concise with what you want and say exactly what you want without it reading like a conversation...

I may unblock you from the YimMenu organisation in the future for now I'm not interested.

**Comment by 7HA7MA77** [comment]
So, you blocked guy who gave 10 good propositions, and you stay on your friend side, ignoring he was bad, and did evil things? ok

**Comment by 7HA7MA77** [comment]
created thread was 
"Add deleting vehicles in persistent vehs when shiftclick"
gir closed that issue, said its shit, and then made update

added "X" icon next to every vehicle, what is spam, and can cause missclick, its my idea but made in worse way.
its stolen, but ruined btw, thats all. you have impostor amongs you, and istead of vote him, you voted someone who was on your side. thats all, sir, have a good day. or a night. bye, man.

**Comment by 7HA7MA77** [comment]
also, i added lot of different propositions, he closed them, and probably he gonna made that things realised without credits for me to being author of that idea. not nice. i am dissapointed, i thought you solve that problem, but you choosen 'bad friend' instead. solution was actually easy, you could just say to him 'ey yo bro, i like you but dont act childish, those ideas was good, you realised one of them, so you kinda agree with that, no matter you commented every of his idea with "its shit, like you", you implemented his ideas, acts speaks louder than words.. so dont delete his ideas, let him be, thats, all, project is our great software, for everyone, its not your private stuff, so dont harm the project again please, think about good of YimMenu instead act like a child. thats all"

**Comment by 7HA7MA77** [comment]
i am giving up here. am i allowed to do my version of YimMenu, just like You did your version of Bigbase, right? 
and obviously You gonna be mentioned there. i appreciate your work. thanks for reply, peace, yo
